### ISSUE TITLE
Script crashes on launch

### ISSUE THREAD

**Issue by wtquin** [compupro/remote-minecraft-server-start-from-discord#1] opened 2021-08-06 16:10 UTC
discord.py now **needs** Python 3.8 or higher to work, so I downloaded the latest python version (3.9.6 64-bit). 
The bot_main.py script closes instantly when opened, and spits out the following error when opened with command prompt:

E:\MC servers\remote-minecraft-server-start-from-discord-master>bot_main.py
Traceback (most recent call last):
  File "E:\MC servers\remote-minecraft-server-start-from-discord-master\bot_main.py", line 11, in <module>
    bot_settings = json.loads(settings_json)
  File "C:\Users\Quint\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Quint\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Quint\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 23 (char 56)

I have filled in the settings.json file and double-checked but couldn't find anything myself.

**Comment by wtquin** [comment] 2021-08-06 16:21
Tried again with version 0.16.6 of discord.py and the last version of python 3.6, but the exact same error is shown.

**Comment by compupro** [comment] 2021-08-06 19:52
Man, this is a really old script! Anyways, since you're on Windows, I suspect the problem is that you need to use double backslashes in your file and directory paths, otherwise the slashes will be treated as escape characters.

Minimally, in order to get the bot running on latest discord.py 1.7.3 + Python 3.9.6, you'll also have to swap out lines with `bot.send_message` with whatever discord.py uses now, or comment it out or replace it with `pass` or something.

Let me know how you get on. If you end up replacing `bot.send_message` and the other bot methods that start with `await` with the newer versions, feel free to make a pull request or something.

**Comment by compupro** [comment] 2021-08-06 19:57
Also I'm really curious how you found this bot!

**Comment by wtquin** [comment] 2021-08-07 02:05
I only realized the script isn't that new midway through and decided just to go for it. Surprisingly there's still no good alternative to this day afaik.
 
I've probably spent over 10 hours spread over 2 weeks googling for something that could turn *on* a server, used to do it using parsec and just remoting into my pc but it uses way too much bandwidth. Then finally found this in some last attempt to find something that'd work.

Also fixed the script and it works with the newest version of discord.py and python now. You were right about the double backslashes. 

No idea how to make a pull request but I'm sure I can figure it out with some googling, I only had to make some minor changes, thanks for the useful script :D

**Comment by compupro** [comment] 2021-08-07 02:40
I'm glad my script has come in handy for you! I just kinda made the script a long time ago and didn't really end up using it, so I'm glad someone's found some utility in it.

You can fork the repo on the top right of the repo page, and then you can commit your new version of the script to your fork's repo. Then in this repo you can go to the Pull Requests tab and make a pull request. Just make sure you don't accidentally check in your bot credentials.

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by compupro** [comment] 2021-08-08 04:31
Since #2 has been merged in, I'm closing this issue.

**Closed as completed by compupro** 2021-08-08 04:31 UTC
